export const POST_BY_DATE_NEW = 'SORT_BY_DATE_NEW';
export const POST_BY_DATE_OLD = 'SORT_BY_DATE_OLD';
export const POST_BY_SCORE_GOOD = 'POST_BY_SCORE_GOOD';
export const POST_BY_SCORE_BAD = 'POST_BY_SCORE_BAD';